name: ðŸ”€ Sync mirror to Gitee

on:
  push:
    branches:
      - main
      - docs
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'TuSimple/naive-ui'
    steps:
      - name: mirror
        continue-on-error: true
        if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
        uses: wearerequired/git-mirror-action@v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:TuSimple/naive-ui.git'
          destination-repo: 'git@gitee.com:naive-ui/naive-ui.git'